name: Execute Project Tests

on:
  push:
    branches:
      - main
    paths:
      - project/**
      - .github/workflows/start-tests.yml

jobs:
  execute-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main

      # Install python
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          pip install -r main/project/requirements.txt

      # Run project tests
      - name: Execute tests
        id: ex_tests
        run: |
          cd main/project
          ./tests.sh | tee result.log

      # Upload full tests report
      - name: Upload tests report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tests-report
          path: main/project/result.log

      # Upload database of test with real data
      - name: Upload database of test-results
        uses: actions/upload-artifact@v4
        with:
          name: test-database
          path: data/data.sqlite
